[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/caloriasDiarias"
to = "/index.html"
status = 200

[[redirects]]
from = "/macronutrientes"
to = "/index.html"
status = 200