[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/caloriasDiarias"
  to = "/caloriasDiarias/index.html"
  status = 200

[[redirects]]
  from = "/macronutrientes"
  to = "/macronutrientes/index.html"
  status = 200